wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1681022172.177078
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 75
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.13.10
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 3
dev_size:
  desc: null
  value: 6
dropout:
  desc: null
  value: 0.25
early_stop:
  desc: null
  value: 100
early_stop_threshold:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.01
model:
  desc: null
  value: mpnet_base_v2
out_activations:
  desc: null
  value: relu
out_linears:
  desc: null
  value: 2
random_seed:
  desc: null
  value: 22
sent_structure:
  desc: null
  value: word0 word1
train_size:
  desc: null
  value: 10
word_activations:
  desc: null
  value: tanh
word_linears:
  desc: null
  value: 1
